// describe('Dashboard Page', () => {
//     beforeEach(()=> {
//         cy.intercept('GET', 'https://one-minute-writer-be.herokuapp.com', { fixture: 'UserData.json' })
//         cy.visit('http://localhost:4000') 
//     })

//     it('Should display the title, header, logo and nav bar', () => {
//         cy.get('h1')
//             .should('exist')
//             .should('have.text', 'One Minute Writer')
//         .get('img')
//             .should('be.visible')
//             .should('have.attr', 'alt')
//         .get('header').should('be.visible')
//         .get('nav').should('be.visible')
//         .get('[data-testid=dashboard-nav-button]')
//             .should('be.visible')
//             // .should('have.css', 'active')
//         .get('[data-testid=start-writing-nav-button]').should('be.visible')
//     })
//     it(`It should display user's name and user's statistics`, () => {
//         cy.get('[data-testid=user-greeting]')
//             .should('have.text', 'Welcome Plutarch')
//         .get('[data-testid=user-stats]')
//             .should('be.visible')
//         .get('[data-testid=words-per-minute]')
//             .should('have.text', 1932)
//         .get('[data-testid=total-words]')
//             .should('have.text', 23243)
//     })
//     it(`Should display the user's stories`, () => {
//         cy.get('[data-testid=stories-section]')
//             .should('be.visible')
//             .should('have.length', 2)
//         .get('[data-testid=single-story]').first()
//             .get('[data-testid=story-title]').should('be.visible')
//             .get('[data-testid=story-date]').should('be.visible')
//             .get('[data-testid=story-body]').should('be.visible')
//     })
// })